### ISSUE TITLE
Getting ID of focused TextInput?

### ISSUE THREAD

**Issue by AshokICreate** [APSL/react-native-keyboard-aware-scroll-view#120]
_**Getting ID of focused TextInput?**_

`<KeyboardAwareScrollView bounces={false} onKeyboardWillShow={(frames) => {
            console.log("Print ID of Focused TextInput")
        }}>`

_Currently i am doing something below but i am not happy with this._

```
        <KeyboardAwareScrollView ref='keyboardAwareScrollView' bounces={false} 
        onKeyboardWillShow={(frames) => {
          const key_board = this.refs.keyboardAwareScrollView;
          const yearID = key_board.props.children.props.children[14].props.id
          const yearLabel = key_board.props.children.props.children[14].props.label
          console.log(key_board.props.children.props.children[14].props.id)
          key_board.props.extraHeight = 300; //is this possible??
        }}>
```

_is it possible to set extraHeight and extraScrollHeight inside onKeyboardWillShow()_

            key_board.props.extraHeight = 300;
            key_board.props.extraScrollHeight = 200;

**_What is expected?_**
      _Directly accessing id of focused TextInput._
       _How can i set extraHeight and extraScrollHeight in onKeyboardWillShow()?_

**_EXPECTED OUTPUT_**
**_I would like to have something like this._**
`        extraScrollHeight={focusedTextInput.label=="Year"?100:0}`

**Comment by alvaromb** [comment]
This is more a React Native question, you should ask there or in StackOverflow because in the end this is a `ScrollView`/`Keyboard` issue, not directly related to the library.

In any case, you can try to listen to the keyboard events and do something like this: https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareMixin.js#L191

If you want, you can send us a PR with an optional callback to fire when the `KeyboardAwareScrollView` component catches the keyboard's events.
