### ISSUE TITLE
Not scrolling on Android

### ISSUE THREAD

**Issue by tallen11** [APSL/react-native-keyboard-aware-scroll-view#155]
This works as expected on iOS but refuses to scroll at all on Android. Anyone run into this? On React-Native 0.47.

**Comment by alvaromb** [comment]
Try the latest release! https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.3.0

Thanks.

**Comment by tallen11** [comment]
Wow, perfect timing, it works as expected now. Thanks!

**Comment by kaushikdas0** [comment]
Does this means it will work on Android without the manifest file change now?

**Comment by Swordsman-Inaction** [comment]
@kaushikdas0 
Still need to set `windowSoftInputMode` to `adjustPan` in `AndroidManifest.xml` for android support.

**Comment by rochapablo** [comment]
I still having problems on Android.

The scroll doesn't work and when I try to scroll the keyboard close it self.

```
<KeyboardAwareScrollView resetScrollToCoords={{ x: 0, y: 0 }} contentContainerStyle={{ flex: 1 }} scrollEnabled>
```

```
android:windowSoftInputMode="adjustPan"
```

**Comment by Swordsman-Inaction** [comment]
@rochapablo `enableOnAndroid` property should be set.

**Comment by rochapablo** [comment]
```
<KeyboardAwareScrollView enableOnAndroid resetScrollToCoords={{ x: 0, y: 0 }} contentContainerStyle={{ flex: 1 }} scrollEnabled>
```

Still not working.

**Comment by hanxk** [comment]
+1

**Comment by jsappme** [comment]
+1 still not working with android

**Comment by jmhuret** [comment]
Hey folks, I had the same issue and I was able to work around it by wrapping the KeyboardAwareScrollView component with a base ScrollView component, set with styles of {flex: 1, alignSelf: 'stretch'}

I realize this doesn't necessarily solve the problem, but it could help you in the near term.

**Comment by rochapablo** [comment]
@jmhuret, I did, but still the same.

**Comment by Swordsman-Inaction** [comment]
@rochapablo remove `contentContainerStyle` then it should work. It seems that `flex: 1` breaks the  whole thing.

**Comment by jjdp** [comment]
flexGrow: 1

**Comment by rochapablo** [comment]
Sorry but it still not working. I'm going to do some more testes and if I got anything I'll let you guys know.

**Comment by jsappme** [comment]
react-native-keyboard-spacer

**Comment by alvaromb** [comment]
Ping @Swordsman-Inaction 

I don't have much experience on Android.

**Comment by Swordsman-Inaction** [comment]
Change `flex: 1` to `flexGrow: 1` works on my side.
@rochapablo Can you share more detail?

**Comment by rochapablo** [comment]
```flexGrow``` work, but only when the keyboard is close

```
<KeyboardAwareScrollView contentContainerStyle={{ flexGrow: 1 }} scrollEnabled>
```

**Comment by LorandP** [comment]
@rochapablo I have not managed to make it work. I have also set adjustPan in manifest but I tried KeyboardAwareScrollView, ScrollView. None worked.

**Comment by rochapablo** [comment]
All still the same (not working)

https://github.com/rochapablo/django

**Comment by MadGeorge** [comment]
Does not work for me too

**Comment by andrei0807** [comment]
Does not work for me too

**Comment by atulmy** [comment]
Combining above hints, it works with following settings:

`/src/Component.js`
```
<KeyboardAwareScrollView contentContainerStyle={{ flexGrow: 1 }} enableOnAndroid={true}>
    ...
</KeyboardAwareScrollView>
```

`/android/app/src/main/AndroidManifest.xml`
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.app">
    ...
    <application ...>
      <activity
        ...
        android:windowSoftInputMode="adjustPan"
      >
       ...
    </application>
</manifest>
```

**Comment by Pianist038801** [comment]
@rochapablo Thanks, it works for me. Super!

**Comment by Drakoun** [comment]
For the people where it is not working, were you using react-navigation (v1) by any chance?

**Comment by prakash224** [comment]
> For the people where it is not working, were you using react-navigation (v1) by any chance?

Yes i am using React Navigation and it does not wor properly

**Comment by Drakoun** [comment]
@prakash224 Well I think it is related. I digged a lot in the source code of react-navigation and nativebase, and I think the issue is from them. What I mean is if on a mock app you try to use only react-native-keyboard-aware-scroll-view just to test it, and without any other libraries as parent component, it should work. If you add them it becomes hell and incoherent. Why ? Because I found they already use react-native-keyboard-aware-scroll-view internally without warning the developer. And why it is hell ? Because there are strange checks and conditions to make it work.

If I remember well, in react-navigation, it is using an another library react-native-tab-view who has keyboard-aware-scroll-view with the scroll on Android. But the thing is on some condition it doesn't use this component but another one, so you loose the native scroll.

On nativebase, the tag `<Content>`,  behind the scene, is by itself a keyboard-aware-scroll-view. I mean if you pass the same props, even if your IDE show warnings that these props doesn't exist, it works.
And now what was the result for me when I wanted to innocently to add my keyboard-aware-scroll-view : on IOS the input scroll too much and disappear to the top xD; on android no scroll and a 'bump' like to the top of few millimeters.
Well I thought these 3 keyboard-aware-scroll-view were conflicting. The other strange thing I had is on android, if it was the first screen of the app, the input scroll was working, but when I used a navigate function from react-navigation to show an another screen, the input scroll was not working. It was my first hint who lead me to dig in the source code. I couldn't exactly find why and make it work and let it like that.

So in the end, what I have to done to make it acceptable :
- I removed my keyboard-aware-scroll-view compoennt I did want to use
- I took the reference of the component `<Content>` of nativebase
- on onfocus function callback of inputs, I call a function like scrollToNode (I don't really remember, I advise you to google it) on the reference.
- Make sure that a parent component doesn't have a `flex:1`, even if what you want to show by itself fit the screen, because on Android it was blocking the scroll for me and then changed them to `flex:0`

The result: on iOS it scrolls a litlle to much but doesn't disappear so it's ok, on Android sometimes there is like a scroll up-down-up but the input is still outside the keyboard so it's ok.
Well I hope you can filter these informations to find your solution and wish you good luck !

N.B : I did explain my approach because when I google any issues of react-native, I only see 'Do these it works', 'I did that and worked' but when I try... meh it doesn't work. So If you find yourself in a similar situation, I hope my solution can help you. But if you are not, this give you some hints.

**Comment by fabiorbap** [comment]
@atulmy solution worked for me

**Comment by tattivitorino** [comment]
I'm in a nightmare with this on Android! Similar situations as @Drakoun 
I'm using NativeBase with the Content element and yes i've checked the source and there it is the KeyboardAwareScrollView. I'm trying everything I could think of and the great nightmare is that i'm using the returnKeyType prop to next since I have a large form. When I touch the Input the Content scrolls, its not perfect but it does, but the focusNext handler has no effect at all!! The Input is focused but the Content does not scroll at all..

If anyone has any idea that could help me fix this I'll be eternally grateful!!! 

Here's what I have in my FormComponent: (removed a few methods for the sake of brevity)

this is my form data model

const formData = [
  {
    name: 'nome',
    label: 'Nome Completo',
    width: '100%',
    required: true,
    validate: [validateRequired],
    next: true,
    keyboardType: 'default',
    textContentType: 'none',
    autoCapitalize: 'words',
    group: 'dados_pessoais'
  },
  {
    name: 'cpf',
    label: 'CPF',
    width: '100%',
    required: true,
    maxLength: 14,
    format: 'cpf',
    validate: [validateRequired, validateCPF],
    next: true,
    hint: 'Digite apenas números',
    keyboardType: 'numeric',
    textContentType: 'none',
    disabledOnEdit: false,
    group: 'dados_pessoais'
  },
and so on...
]

This is my FormComponent

`import React, { Component } from 'react';
import { View, Keyboard, StyleSheet, Platform, KeyboardAvoidingView } from 'react-native';
import { Content, Item, Input, Label, Body, Button, Text, Card, CardItem, Icon } from 'native-base';
import { Field, reduxForm, formValueSelector, change } from 'redux-form';
import { validateEmail, validateRequired } from '../../../utils';

import { connect } from 'react-redux';
import { createClienteRequest, updateClienteRequest } from '../../../store/actions';
import { fetchAddressByCep } from '../../../api/external.api';
import { formatString, reverseDate } from '../../../utils';

import styles from '../styles';
import { formData } from './formData';

class ClienteForm extends Component {

  constructor(props) {
    super(props);
    
    this.inputs = {}; //this is used to keep track of the inputs and call input.focus()

    this.state = {
      activeInputIndex: 0,
      nextDisabled: false,
      previousDisabled: true
    }
  }

  handleFocus = index => {
    this.setState({
      activeInputIndex: index,
      nextDisabled: index === formData.length - 1,
      previousDisabled: index === 0
    })
  }

  focusPrevious = () => {
    const { activeInputIndex, previousDisabled } = this.state;
    if (previousDisabled) return;
    const input = this.inputs[activeInputIndex - 1];
    const el = input._root ? input._root : input.getElement()._root; // either NativeBase Input ref or TextInputMask ref
    el.focus();
  }

  focusNext = () => {
    const { activeInputIndex, nextDisabled } = this.state;
    if (nextDisabled) return;
    const input = this.inputs[activeInputIndex + 1];
    const el = input._root ? input._root : input.getElement()._root; // either NativeBase Input ref or TextInputMask ref
    el.focus();
  }

  getInput = (input, custom) => {

    const { next, index, keyboardType, textContentType, autoCapitalize, maxLength, editable } = custom;
    const i = parseInt(index);

    return (
      <Input {...input}
        ref={ref => this.inputs[i] = ref}
        editable={editable}
        underlineColorAndroid="transparent"
        keyboardType={keyboardType}
        textContentType={textContentType}
        autoCapitalize={autoCapitalize ? autoCapitalize : "none"}
        maxLength={maxLength ? maxLength : null}
        returnKeyType={next ? "next" : "done"}
        onFocus={() => {
          this.handleFocus(i)
        }}
        blurOnSubmit={next ? false : true}
        onSubmitEditing={() => {
          if (next) this.focusNext();
        }} />
    )
  }

  renderInput = ({ input, label, type, meta: { touched, error }, ...custom }) => {

    const { width, required, hint } = custom;
    let hasError = false;
    if (touched && error !== undefined) {
      hasError = true;
    }
    return (
      <View style={[styles.field, { width: width }]}>
        <Item stackedLabel error={hasError}>
          <Label>{label}:{required ? <Text danger>**</Text> : null}</Label>
          {hint ? <Text medium style={styles.hint}>{hint}</Text> : null}
          {this.getInput(input, custom)}
        </Item>
        {hasError ? <Text style={styles.fieldErrorMessage}>{error}</Text> : null}
      </View>
    );
  }


  renderFormFields = group => {
    return formData.map((field, index) => {

      if (field.group == group) {

        const { label, name, disabledOnEdit, width, required, hint, validate, next, keyboardType, textContentType, parse, format, autoCapitalize, maxLength } = field;

        return (
          <Field
            key={`input_${index}`}
            label={label}
            name={name}
            editable={disabledOnEdit && this.props.formType == 'edit' ? false : true}
            parse={value => {
              if (parse == 'trim') return value ? value.trim() : value
              return value;
            }}
            format={value => {
              switch (format) {
                case 'cpf':
                case 'dt-br':
                case 'cep':
                case 'ddd-phone':
                case 'ddd-mobile':
                  if (value === null || value === '') return null;
                  return formatString(value, format);
                default:
                  return value;
              }
            }}
            width={width}
            required={required ? required : false}
            hint={hint ? hint : false}
            component={this.renderInput}
            validate={validate ? validate : null}
            next={next}
            index={index}
            keyboardType={keyboardType}
            textContentType={textContentType}
            autoCapitalize={autoCapitalize}
            maxLength={maxLength}
            onChange={this.onFieldChange} />
        );
      }
    })
  }  

  render() {
    const { handleSubmit, pristine, submitting } = this.props;
    return (

      <Content
        viewIsInsideTabBar={true}
        disableKBDismissScroll={true}
        enableOnAndroid={true}>
        <View style={{ padding: 15 }}>

          <Card>
            <CardItem header>
              <Text secondary>Dados Pessoais</Text>
            </CardItem>
            <CardItem>
              <Body>
                <Text medium>Preencha corretamente todos os campos abaixo</Text>
                <Text medium>Campos marcados com <Text danger>**</Text> são obrigatórios</Text>

                <View style={[styles.fieldsContainer]}>

                  {this.renderFormFields('dados_pessoais')}

                </View>

              </Body>
            </CardItem>
          </Card>

          <Card>
            <CardItem header>
              <Text secondary>Endereço</Text>
            </CardItem>
            <CardItem>
              <Body>
                <Text medium>Preencha corretamente todos os campos abaixo</Text>
                <Text medium>Campos marcados com <Text danger>**</Text> são obrigatórios</Text>

                <View style={[styles.fieldsContainer]}>

                  {this.renderFormFields('endereco')}

                </View>

              </Body>
            </CardItem>
          </Card>

          <View style={[styles.buttonsBar, { flexDirection: 'column' }]}>
            <Button secondary style={[styles.button, { width: '60%', alignSelf: 'center' }]}
              disabled={submitting}
              onPress={handleSubmit(this.send)}>
              <Text>Salvar Dados</Text>
            </Button>
          </View>

        </View>
      </Content>

    );
  }
}

const mapStateToProps = (state, ownProps) => {
  const { cliente, error } = state.clientes;
  const { formType } = ownProps;
  const data_nascimento = cliente.data_nascimento ? reverseDate(cliente.data_nascimento) : null;
  const initValues = formType == 'edit' ? { ...cliente, data_nascimento } : null;
  return { cliente, error, initialValues: initValues };
}

ClienteForm = reduxForm({
  form: 'cliente',
  touchOnBlur: false,
  onSubmitSuccess: (result, dispatch, props) => {
    if (props.formType == 'add' && !props.error) props.reset();
  },
  onSubmitFail: (errors, dispatch, submitError, props) => { }
})(ClienteForm);
ClienteForm = connect(mapStateToProps, {
  change,
  createClienteRequest,
  updateClienteRequest
})(ClienteForm)

export default ClienteForm;
`

**Comment by Drakoun** [comment]
Hey @tattivitorino, are you wrapping perhaps your input by an `<Item floatingLabel>` ?
If I am not mistaken, I advise you to use `getRef=` and not `ref=` to get the reference from the Input component. This is something tricky in NativeBase ! I think your issue is from here.
Here one reference https://stackoverflow.com/questions/52523092/native-base-input-refs-not-being-set/52523488#52523488, you can find others references as well in github issues.

**Comment by enso123456** [comment]
Thanks this works

**Comment by enso123456** [comment]
> Combining above hints, it works with following settings:
> 
> `/src/Component.js`
> 
> ```
> <KeyboardAwareScrollView contentContainerStyle={{ flexGrow: 1 }} enableOnAndroid={true}>
>     ...
> </KeyboardAwareScrollView>
> ```
> 
> `/android/app/src/main/AndroidManifest.xml`
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>     package="com.app">
>     ...
>     <application ...>
>       <activity
>         ...
>         android:windowSoftInputMode="adjustPan"
>       >
>        ...
>     </application>
> </manifest>
> ```

thanks this works on my end.

**Comment by jona4life** [comment]
This should solve the issue:
enableOnAndroid={true}

According to:
https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/379#issuecomment-535950165

**Comment by trungtran1** [comment]
> flexGrow: 1

That's worked for me! Thanks a lot 💯

**Comment by DibyajyotiMishra** [comment]
```
_scrollToInput = (reactNode: any) => {
    this.scroll._internalFiberInstanceHandleDEV.memoizedProps.scrollToFocusedInput(
      reactNode,
    );
  };
```

With this it works.

**Comment by ndpiparava** [comment]
Here is my expo app.json
```

 "android": {
      "package": "com.app.flewber",
      "adaptiveIcon": {
        "foregroundImage": "./src/assets/images/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      },
      "googleServicesFile": "./google-services.json",
      "userInterfaceStyle": "automatic",
      "softwareKeyboardLayoutMode": "pan",
      "config": {
      
        "windowSoftInputMode": "adjustPan"
      }
    },
```

   ```
 return (
      <KeyboardAwareScrollView
        resetScrollToCoords={{ x: 0, y: 0 }}
        scrollEnabled={true}
        enableAutomaticScroll={true}
        extraScrollHeight={180}
        enableOnAndroid={true}
        keyboardShouldPersistTaps='handled' // also tried always same result
        extraHeight={Platform.select({ android: 180 })}
        contentContainerStyle={{ flexGrow: 1 }}
        {...props}
      >
        {props.children}
      </KeyboardAwareScrollView>
    );
```
It only works when you select first input and once keyboard is open you go down by keep selecting fields it does not work.

If you dismiss keyboard and select bottom field it works, it does not work when keyboard is already open
