### ISSUE TITLE
Keyboard scrolling to top when "Hardware" keyboard connected

### ISSUE THREAD

**Issue by rknell** [APSL/react-native-keyboard-aware-scroll-view#195]
When the hardware keyboard is not connected, the scroll view is behaving as expected.

However, when I use "Connect Hardware Connected" in the iOS simulator (I don't have a hardware keyboard on hand for iOS) the scrollview keeps returning to the top after editing.

**Comment by cnxtwang** [comment]
For me, this issue appear because the input onChange function trigger too many actions, so that onScroll has been blocked, this time, i scroll the page, after actions has been done, the keyboard disappear, it scroll back to the input, sometime scroll to the top. so i set `        enableResetScrollToCoords={false}
` that fix my issue.
