### ISSUE TITLE
Clicking on new field causes blur to occur

### ISSUE THREAD

**Issue by kevinansley** [APSL/react-native-keyboard-aware-scroll-view#202]
On Android, when I am currently on a TextInput and touch on a new field, the keyboard goes away, but the field I just touched is no longer selected.

Ideal behavior would be to focus on the new TextInput, keep the keyboard open (or switch keyboard if type is different), and scroll to new position.

**Comment by kevinansley** [comment]
Great! Closing out as the issue is a bigger, React-native issue. Thanks!

**Comment by angly-cat** [comment]
> Looks like this is fixed here: facebook/react-native@8cf36d8

> It looks like it hasn't been merged to master though. :/

[Related PR](https://github.com/facebook/react-native/pull/16889).

**Comment by angly-cat** [comment]
@kevinansley I tried to use forked `react-native` with the fix @coderdave suggested, but it didn't work. And it shouldn't have worked, because `keyboardDismissMode='on-drag'` (behavior of which that fix addresses) isn't used in this repo. And even when I use `ScrollView` with two `TextInput`s, the issue persists.

So, it's definitely something within `react-native` itself.

**Comment by angly-cat** [comment]
And apparently it's the intended behavior.

@kevinansley if you still have this issue, it's actually related to facebook/react-native#17434. And there's the fix right there in [this comment](https://github.com/facebook/react-native/issues/17434#issuecomment-355737942). I added `keyboardShouldPersistTaps="handled"` prop to `KeyboardAwareScrollView` and voila.

**Comment by kevinansley** [comment]
Thanks angly-cat! I ended up finding a solution by using NativeBase Container, Content, and Input controls
