### ISSUE TITLE
Doesn't work with autofill

### ISSUE THREAD

**Issue by munkhorgil** [APSL/react-native-keyboard-aware-scroll-view#212]
If textinput is password with secureTextEntry props it will use autofill automatically, When I type the keyboard autofill came up and focus to textinput, But suddenly it scrolls to 0, 0 when autofill dissappear. as a result texinput will be behind the keyboard. Any solution?

- React 16.0.0
- React Native 0.51.0
- Keyboard-aware-scroll-view 0.4.1
- iOS 11.2.1

**Comment by alvaromb** [comment]
Can you test the new release? https://github.com/APSL/react-native-keyboard-aware-scroll-view/releases/tag/v0.4.2

Ping me if this issue still persists and I'll reopen.

Thanks.

**Comment by rahamin1** [comment]
I am having a problem in 0.8.0. I am adding the details in #325

**Comment by acollazomayer** [comment]
Same Issue here. This should not be closed. I am using latest version

**Comment by AntoniusGolly** [comment]
Still exists in 0.9.4, but I tested with ScrollView, too. Meaning, when you replace <KeyboardAwareScrollView> with <ScrollView> it is the same behavior. Only in <KeyboardAvoidingView> (no scroll) the autofill is always showing up.

Please try with <ScrollView>. If it exists there, closing this issue seems right.
