### ISSUE TITLE
View doesnot come to its original position after it moves up.

### ISSUE THREAD

**Issue by susylPearl** [APSL/react-native-keyboard-aware-scroll-view#36]
When i input text in textfield, the textfield moves up and provides user to input , but when i completed inputing text and click on done, the textinput field doesnot comes to its original place, i have enabled alwaysBounceVertical={true} and scrollEnabled={false}. what had happened now? i think the view should comes to its original place after text input task is finished.

**Comment by alvaromb** [comment]
You have to blur your input on the `onSubmitEditing` method: http://facebook.github.io/react-native/releases/0.27/docs/textinput.html#textinput

**Comment by ms88privat** [comment]
@alvaromb I have the same problem and nothing seems to help here :(

**Comment by ms88privat** [comment]
@alvaromb I found the solution to my problem:

If I [remove this line](https://github.com/APSL/react-native-keyboard-aware-scroll-view/blob/master/lib/KeyboardAwareScrollView.js#L28), everything works like expected 👍 (I'm also not quite sure for what you need this, only if you use the native ios tabbar?)

**Comment by alvaromb** [comment]
That line is what resizes the `ScrollView` when the keyboard appears. Sorry but I don't follow what's the issue you're getting. Can you show me a gif of what's actually happening?

**Comment by ms88privat** [comment]
Thanks for your help. 

What is the resize needed for? Whats the use case here? It does scroll to the input anyway?

Step 1 (no space between header and content)

![image](https://cloud.githubusercontent.com/assets/6705521/16480618/719e013a-3ea7-11e6-9b6b-14e6684efdce.png)

Step 2 (focus one input, ScrollView will scroll to)

![image](https://cloud.githubusercontent.com/assets/6705521/16480640/98d7e626-3ea7-11e6-8085-976cc160781b.png)

Step 3 (see space between header and content, always the same space, no matter the input field I focused)

![image](https://cloud.githubusercontent.com/assets/6705521/16480666/b5abcefc-3ea7-11e6-9976-ea15cc59396a.png)

The whole ScrollView has somehow more marginTop (because even the ScrollBar starts below). It does not happen with a normal ScrollView and it does not happen if I remove the contentInset. Setting contentInset to 0 does NOT solve this problem.

![image](https://cloud.githubusercontent.com/assets/6705521/16480742/26c52afc-3ea8-11e6-8ed3-afdeeff17d04.png)

![image](https://cloud.githubusercontent.com/assets/6705521/16480745/2aff4260-3ea8-11e6-9311-0a87befddb6d.png)

**Comment by alvaromb** [comment]
If your form inside the scroll view is bigger than the scroll viewport, if you don't adjust the content inset you'll not be able to scroll the content behind the keyboard. It's one of the main features of this library and it's independent of the auto scroll behaviour.

**Comment by ms88privat** [comment]
I think I got what you are telling. It doesn't matter for me because the viewport of my scrollview will expand with my form itself? e.g. the whole page is a scrollView and not only a small section within it, right?
