### ISSUE TITLE
android no UIManager.viewIsDescendantOf

### ISSUE THREAD

**Issue by MingYe-dz** [APSL/react-native-keyboard-aware-scroll-view#63]
The android version no UIManager.viewIsDescendantOf method. So 
 // Automatically scroll to focused TextInput
    if (this.props.enableAutoAutomaticScroll) {
      const currentlyFocusedField = TextInput.State.currentlyFocusedField()
      if (!currentlyFocusedField) {
        return
      }
      UIManager.viewIsDescendantOf(
        currentlyFocusedField,
        this.getScrollResponder().getInnerViewNode(),
        (isAncestor) => {
          if (isAncestor) {
            this.scrollToFocusedInputWithNodeHandle(currentlyFocusedField)
          }
        }
      )
    }

this code has problem. How solve it?

**Comment by willotter** [comment]
I got this issue because my react native version was outdated so worth checking. 0.2.0 support RN `~0.32.0`

**Comment by atlas1119** [comment]
![image](https://cloud.githubusercontent.com/assets/9478646/26818205/578fbef0-4acc-11e7-9e9c-e5d21a0f6ca4.png)

react native  0.44.0,     this react-native-keyboard-aware-scroll-view version is 0.2.9

**Comment by Swordsman-Inaction** [comment]
https://github.com/facebook/react-native/pull/13129 has been merged, so Android will have  `UIManager.viewIsDescendantOf` on 0.45. And I'll add Android support later.

@atlas1119 It's weird. The `updateKeyboardSpace` should never be called on Android since there is no `keyboardWillShow` event on Android. How did you get this?
