### ISSUE TITLE
Keyboard Avoiding View (RN Core)

### ISSUE THREAD

**Issue by jhabdas** [APSL/react-native-keyboard-aware-scroll-view#66]
Given `KeyboardAvoidingView` is now in Core it would be great to see efforts shifted to help make that component better rather than running down two different roads:

https://facebook.github.io/react-native/docs/keyboardavoidingview.html

**Comment by alvaromb** [comment]
Hello @jhabdas!

This component existed _before_ Facebook open sourced their keyboard component, so this is why it kept evolving. I haven't tested RN's component yet, but as I stated before in other issues (https://github.com/APSL/react-native-keyboard-aware-scroll-view/issues/56#issuecomment-241463595) I'm looking forward to have some time to test it and I would be more than happy to deprecate this package in favour of the official one.

Thanks.

**Comment by jhabdas** [comment]
@alvaromb with all due respect, by closing this issue you've stopped my intent in opening it. The purpose and goal here is to increase awareness. Competition is good, but fragmentation hurts.

**Comment by alvaromb** [comment]
Hello Josh!

First of all, there's already an open issue about the RN official keyboard component, so this issue doesn't add any useful information and it's duplicated. I maintain 7 repos by myself and collaborate in others, so for me it's better to have less issues opened and try not to have duplicates. Time matters, and matters more when most of this job is made during family time and not at the office. 

There's nothing about competition here. I made this component because at that time there wasn't this functionality implemented and hopefully I helped other devs with it. Now that RN has an official component that does the same and probably it does it better, I encourage people to look at the official solution. But for my use case, I haven't had time yet to test the official component, so I'm waiting to make an official announcement of deprecation till I can confirm that the official component is useful for the use cases this component was made. 

Thank you. 

Enviado desde mi iPhone
