### ISSUE TITLE
the code in android made the app die

### ISSUE THREAD

**Issue by ANWSY** [APSL/react-native-keyboard-aware-scroll-view#68]
if(Platform.OS === 'android') {

```
     try {
       this.scrollToFocusedInputWithNodeHandle(currentlyFocusedField)
     } catch (e) {

     }
  } else {
    UIManager.viewIsDescendantOf(
        currentlyFocusedField,
        this.getScrollResponder().getInnerViewNode(),
        (isAncestor) => {
          if (isAncestor) {
            // Check if the TextInput will be hidden by the keyboard
            UIManager.measureInWindow(currentlyFocusedField, (x, y, width, height) => {
              if (y + height > frames.endCoordinates.screenY) {
                this.scrollToFocusedInputWithNodeHandle(currentlyFocusedField)
              }
            })
          }
        }
    )
  }
```

**Comment by alvaromb** [comment]
Please, in the meantime disable the automatic scrolling under Android:

```js
enableAutoAutomaticScroll={(Platform.OS === 'ios') ? true : false}
```

**Comment by ANWSY** [comment]
that means this component doesn't work in the Android Platform . 
such as this statement '
this.scrollToFocusedInputWithNodeHandle(currentlyFocusedField)
' will made the app die ?

**Comment by alvaromb** [comment]
There is no `UIManager.viewIsDescendantOf` in Android yet. The problem is that if you have multiple scroll views in the same scene, all will listen to the keyboard event but only one contains the `TextInput` children, so the ones without it will crash. The descendant method avoided the crash under iOS, but I haven't had time yet to send a PR for Android.
