### ISSUE TITLE
Restore position with keyboardShouldPersistTaps

### ISSUE THREAD

**Issue by eth3lbert** [APSL/react-native-keyboard-aware-scroll-view#90]
Thanks for the great component.

When using this component with props `keyboardShouldPersistTaps`, the restore position is incorrect and left extra space out there.

The scenario: focus to the last textInput and then focus to previous texinput and dismiss the keyboard.

**Comment by alvaromb** [comment]
Hi! Do you have `automaticallyAdjustContentInsets` set to `false`?

**Comment by eth3lbert** [comment]
No, i don't.

**Comment by alvaromb** [comment]
Ok, try to set it to `false` and check if the extra space is present.

**Comment by eth3lbert** [comment]
Sorry, its not work. 
![screen_shot_2017-01-10_at_16_18_00](https://cloud.githubusercontent.com/assets/2889664/21798732/feab7bf6-d750-11e6-859b-aca0a5f5e3d1.jpg)

**Comment by alvaromb** [comment]
May I see your source code?

**Comment by eth3lbert** [comment]
```jsx
      <KeyboardAwareScrollView keyboardShouldPersistTaps ref="scroll">
        <AddressList isEditing={this.state.isEditing} onAdd={this.onAdd}
          onDelete={this.onDelete} onDefault={this.onDefault} rows={rows}/>
      { this.state.isEditing && (
          <AddressForm
            onChange={this.onChange}
            onSave={this.onSave}
            onCancel={this.onCancel}
            form={form}
            value={this.state.value}
          />)
      }

      </KeyboardAwareScrollView>

```
`AddressForm`:
```jsx
      <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
        <View style={styles.container}>
          <Form ref='form'
            type={this.getType(this.props.value)}
            value={this.props.value}
            onChange={this.props.onChange}
            options={options}
          />
          <View style={styles.btnContainer}>
          <Button
            style={styles.saveBtn}
            isDisabled={false}
            onPress={this.props.onSave}
          >
            {'Save'}
          </Button>
          <Button
            style={styles.cancelBtn}
            isDisabled={false}
            onPress={this.props.onCancel}
          >
            {'Cancel'}
          </Button>
        </View>
      </View>
    </TouchableWithoutFeedback>

```

**Comment by alvaromb** [comment]
Ok, try to wrap your `KeyboardAwareScrollView` with a `View` component with flex: 1.

**Comment by eth3lbert** [comment]
Thanks, but it still not work.

The position could restore perfectly when you focus one input and dismiss, but it fails when focus input continuously then dismiss.

**Comment by alvaromb** [comment]
Sorry, I'll try to reproduce it. I'm currently using `keyboardShouldPersistTaps` with all my apps and this component and I don't see this error happening.

Sad!

**Comment by kevinvn1709** [comment]
@eduherraiz 
You can try `automaticallyAdjustContentInsets` props set to `false`

**Comment by guimello** [comment]
I'm experiencing a similar issue.

```html
<View style={{flex: 1}}>
          <KeyboardAwareScrollView
            keyboardShouldPersistTaps={false}
            automaticallyAdjustContentInsets={false}
            bounces={false}
            showsVerticalScrollIndicator={false}
          >
// Two TextInput inside
....
```

What happens is that the scrollview does not need to scroll because its content is not bigger than its size. So when a tap the first input and tap, this plugin works correctly (scrolls to the text input being edited and later scrolls to its older position.

But if a tap the first textinput and later with the keyboard still up, tap the second one, which will transfer the focus from one another and then later tap outside, the scrollview will scroll based on the second textinput offtset and clip the scrollview content. Because the view is not scrollable (its content does not require scroll based on its size), I can't access the top view functions on my layout (there are some buttons actually inside the scrollview before the textinputs).


I'm using react-native 0.37, but I don't think it is related to that.

**Comment by alvaromb** [comment]
Please use `v0.2.7` and test again your issue. I will reopen if the issue is still present.
